<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunctionsExternal\FunctionsExternal.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="ExcelDna.AddIn" Version="1.9.0" />
    <PackageReference Include="ExcelDna.IntelliSense" Version="1.9.0" />
  </ItemGroup>

</Project>
